import numpy as np
import tqdm
from datareader import Data_Reader
import pandas as pd


class Prepare_Vocabulary(object):
    def __init__(self, datareader, filename):
        self.reader = datareader
        self.filename = filename
    
    def get_labels_and_data(self):
        # following line generate iterator which yields each line (which has 1x3 dimension)
        reader_iterator = self.reader.iterate_data_file()
        data = []
        labels = []
        for each_sentence in reader_iterator:
            for each in each_sentence:
                data.append(each['form'])
                labels.append(each['lemma'])
        
        # generate raw data as a dictionary which will be used to build pandas dataframe
        raw_data = {"word": data, "POS": labels}
        return raw_data

    def generate_dataframe(self):
        # following line will give us dictionary, word: list of words; pos: list of pos'es
        raw_data_dictionary = self.get_labels_and_data()
        # pandas dataframe has been generated by the following line. nx2 dimensional dataframe, where n is the number of raw data.
        # There will be 2 columns, "word" and "POS"
        main_dataframe = pd.DataFrame(raw_data_dictionary)
        return main_dataframe

    def generate_vocabulary(self):
        dataframe = self.generate_dataframe()
        # unique data and labels are generated here as lists
        unique_data = ["<unk>","<pad>"]
        unique_labels = ["<pad>"]
        # pd.unique(df) generates the list of unique tokens from the whole data. We add unique lists to them.
        unique_data += list(pd.unique(dataframe["word"]))
        unique_labels += list(pd.unique(dataframe["POS"]))
        # data vocabulary is generated here such as : key is word, and value is its index. The same is done for labels
        data_vocabulary = {}
        labels_vocabulary = {}
        for index, each  in enumerate(unique_data):
            data_vocabulary[each] = index
        for index, each in enumerate(unique_labels):
            labels_vocabulary[each] = index
        return data_vocabulary, labels_vocabulary

